
edge_config:
  bootstrap: >-
    https://edgemicroservices-eu-west-1.apigee.net/edgemicro/bootstrap/organization/emea-demo7/environment/test
  jwt_public_key: 'https://emea-demo7-test.apigee.net/edgemicro-auth/publicKey'
  managementUri: 'https://api.enterprise.apigee.com'
  vaultName: microgateway
  authUri: 'https://%s-%s.apigee.net/edgemicro-auth'
  baseUri: >-
    https://edgemicroservices.apigee.net/edgemicro/%s/organization/%s/environment/%s
  bootstrapMessage: Please copy the following property to the edge micro agent config
  keySecretMessage: The following credentials are required to start edge micro
  products: 'https://emea-demo7-test.apigee.net/edgemicro-auth/products'
edgemicro:
  port: 8000
  max_connections: 1000
  config_change_poll_interval: 600
  logging:
    level: error
    dir: /var/tmp
    stats_log_interval: 60
    rotate_interval: 24
  plugins:
    sequence:
      - oauth
      - spikearrest
      - quota

spikearrest:
  timeUnit: minute
  allow: 100
  buffersize: 0

headers:
  x-forwarded-for: true
  x-forwarded-host: true
  x-request-id: true
  x-response-time: true
  via: true
oauth:
  allowNoAuthorization: false
  allowInvalidAuthorization: false
  verify_api_key_url: 'https://emea-demo7-test.apigee.net/edgemicro-auth/verifyApiKey'
analytics:
  uri: >-
    https://edgemicroservices-eu-west-1.apigee.net/edgemicro/axpublisher/organization/emea-demo7/environment/test
  bufferSize: 10000
  batchSize: 500
  flushInterval: 5000









eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJhcGlfcHJvZHVjdF9saXN0IjpbIkVkZ2VtaWNybyBEZW1vIFByb2R1Y3QiXSwiYXVkaWVuY2UiOiJtaWNyb2dhdGV3YXkiLCJqdGkiOiJkZTE0ZjdlNi02NzU4LTRiNDktOGYxNi05YWU1ZWU0Y2JjYmIiLCJpc3MiOiJodHRwczovL2VtZWEtZGVtbzctdGVzdC5hcGlnZWUubmV0L2VkZ2VtaWNyby1hdXRoL3Rva2VuIiwiYWNjZXNzX3Rva2VuIjoiRDFwUDdIdkpja3dBQXh6N0lnMkZXZWphOUdxdiIsImNsaWVudF9pZCI6IlVuTWhjMEtZMUFGSWtaVUF0V0NvenZOQkpNWkZVS24zIiwibmJmIjoxNTE3MDg3NTUxLCJpYXQiOjE1MTcwODc1NTEsImFwcGxpY2F0aW9uX25hbWUiOiJkY2UyMzY2My05ODkzLTRiZGMtOWM5OS1lMmM2NGMxZjlkYTMiLCJzY29wZXMiOlsiIl0sImV4cCI6MTUxNzA4Nzg1MX0.E1LmFwimZv5U2Kx9HXx36Nxh5SZCr8881rcvXhMwLh6DjyaiqA25mKp4wtU-4GingpRYZgDEHKb1pHNxDmJmZ_8k91Mz7DdMZjmVZJtfOHBH2zTTZphBekE40t3xRot8YT8dEp04ukM0Fy5jCofhWtCIAMgprAD-SS6OrHT6OV3c3_lOiWW0S9ToPZFpuD6q7Lw84CtARC4KyxFUN7lt3csYetEdZuMuRrQ-ffm9LHA07uDRUF5MUTt_DvMWfInz5cKSDdRsxmBFPu-s3RsF2eB-vMIMX6qI8ZSBgsjJgBTTsyGwmWv8z-se_YVg2oDaszaWPPhM_ne_aaSEPcFYaQ


curl -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJhcGlfcHJvZHVjdF9saXN0IjpbIkVkZ2VtaWNybyBEZW1vIFByb2R1Y3QiXSwiYXVkaWVuY2UiOiJtaWNyb2dhdGV3YXkiLCJqdGkiOiJkZTE0ZjdlNi02NzU4LTRiNDktOGYxNi05YWU1ZWU0Y2JjYmIiLCJpc3MiOiJodHRwczovL2VtZWEtZGVtbzctdGVzdC5hcGlnZWUubmV0L2VkZ2VtaWNyby1hdXRoL3Rva2VuIiwiYWNjZXNzX3Rva2VuIjoiRDFwUDdIdkpja3dBQXh6N0lnMkZXZWphOUdxdiIsImNsaWVudF9pZCI6IlVuTWhjMEtZMUFGSWtaVUF0V0NvenZOQkpNWkZVS24zIiwibmJmIjoxNTE3MDg3NTUxLCJpYXQiOjE1MTcwODc1NTEsImFwcGxpY2F0aW9uX25hbWUiOiJkY2UyMzY2My05ODkzLTRiZGMtOWM5OS1lMmM2NGMxZjlkYTMiLCJzY29wZXMiOlsiIl0sImV4cCI6MTUxNzA4Nzg1MX0.E1LmFwimZv5U2Kx9HXx36Nxh5SZCr8881rcvXhMwLh6DjyaiqA25mKp4wtU-4GingpRYZgDEHKb1pHNxDmJmZ_8k91Mz7DdMZjmVZJtfOHBH2zTTZphBekE40t3xRot8YT8dEp04ukM0Fy5jCofhWtCIAMgprAD-SS6OrHT6OV3c3_lOiWW0S9ToPZFpuD6q7Lw84CtARC4KyxFUN7lt3csYetEdZuMuRrQ-ffm9LHA07uDRUF5MUTt_DvMWfInz5cKSDdRsxmBFPu-s3RsF2eB-vMIMX6qI8ZSBgsjJgBTTsyGwmWv8z-se_YVg2oDaszaWPPhM_ne_aaSEPcFYaQ" http://localhost:8000/v1/hib-demo-api/get


